-- 1. Create the Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name text NOT NULL,
    record_id bigint NOT NULL,
    operation text NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    old_data jsonb,
    new_data jsonb,
    changed_at timestamptz DEFAULT now(),
    changed_by uuid DEFAULT auth.uid() -- Capture the user ID if available
);

-- Enable RLS on audit_logs (optional, but good practice)
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users (adjust as needed for admins)
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."audit_logs";

CREATE POLICY "Enable read access for all users" ON "public"."audit_logs"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- 2. Create the Trigger Function
CREATE OR REPLACE FUNCTION public.log_member_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO public.audit_logs (table_name, record_id, operation, new_data, changed_by)
        VALUES (TG_TABLE_NAME, NEW.id, TG_OP, row_to_json(NEW)::jsonb, auth.uid());
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        -- Only log if actual data changed (ignoring updated_at if you have it)
        IF NEW IS DISTINCT FROM OLD THEN
            INSERT INTO public.audit_logs (table_name, record_id, operation, old_data, new_data, changed_by)
            VALUES (TG_TABLE_NAME, OLD.id, TG_OP, row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb, auth.uid());
        END IF;
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO public.audit_logs (table_name, record_id, operation, old_data, changed_by)
        VALUES (TG_TABLE_NAME, OLD.id, TG_OP, row_to_json(OLD)::jsonb, auth.uid());
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$;

-- 3. Create the Trigger on 'members' table
DROP TRIGGER IF EXISTS trigger_member_audit ON public.members;

CREATE TRIGGER trigger_member_audit
AFTER INSERT OR UPDATE OR DELETE ON public.members
FOR EACH ROW
EXECUTE FUNCTION public.log_member_changes();
