-- ==========================================
-- FIX: Withdrawal Rejection & Fee Tracking Logic
-- ==========================================

-- 1. Ensure 'status' column exists in withdrawal_fees_log
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'withdrawal_fees_log' AND column_name = 'status') THEN
        ALTER TABLE withdrawal_fees_log ADD COLUMN status text DEFAULT 'pending';
    END IF;
END $$;

-- 2. Create the Trigger Function
CREATE OR REPLACE FUNCTION handle_withdrawal_update()
RETURNS TRIGGER AS $$
DECLARE
  v_user_id uuid;
BEGIN
  -- Fetch the user_id associated with the agent
  SELECT user_id INTO v_user_id
  FROM agents
  WHERE id = NEW.agent_id;

  -- SYNC STATUS to Fees Log
  UPDATE withdrawal_fees_log
  SET status = NEW.status
  WHERE withdrawal_request_id = NEW.id;

  -- Handle REJECTION
  IF NEW.status = 'rejected' AND OLD.status != 'rejected' THEN
    -- A. Refund the Wallet (Add back the GROSS amount that was deducted)
    -- This effectively refunds the fee and tax as well.
    UPDATE agent_wallets
    SET balance = balance + NEW.gross_amount
    WHERE agent_id = NEW.agent_id;

    -- B. Notify Agent
    IF v_user_id IS NOT NULL THEN
      INSERT INTO notifications (user_id, title, message, type, created_at, is_read)
      VALUES (
        v_user_id,
        'Withdrawal Rejected',
        'Your withdrawal request for ₱' || NEW.gross_amount || ' has been rejected. The amount has been refunded to your wallet.',
        'withdrawal_status',
        NOW(),
        false
      );
    END IF;
  END IF;

  -- Handle APPROVAL
  IF NEW.status = 'approved' AND OLD.status != 'approved' THEN
    -- A. Notify Agent (Balance was already deducted upon request)
    IF v_user_id IS NOT NULL THEN
      INSERT INTO notifications (user_id, title, message, type, created_at, is_read)
      VALUES (
        v_user_id,
        'Withdrawal Approved',
        'Your withdrawal request for ₱' || NEW.gross_amount || ' has been approved.',
        'withdrawal_status',
        NOW(),
        false
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Attach Trigger to Table
DROP TRIGGER IF EXISTS on_withdrawal_update ON withdrawal_requests;

CREATE TRIGGER on_withdrawal_update
AFTER UPDATE ON withdrawal_requests
FOR EACH ROW
EXECUTE FUNCTION handle_withdrawal_update();

-- 4. (Optional) Create notifications table if it doesn't exist (Safety check)
CREATE TABLE IF NOT EXISTS notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  message text not null,
  type text default 'info', 
  is_read boolean default false,
  target_role text,
  extra jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
