-- Run this in your Supabase SQL Editor to fix the withdrawal function, add columns, and create fees log table

-- 1. Ensure columns exist in withdrawal_requests (Idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'withdrawal_requests' AND column_name = 'tax') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN tax numeric DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'withdrawal_requests' AND column_name = 'fee') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN fee numeric DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'withdrawal_requests' AND column_name = 'net_amount') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN net_amount numeric DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'withdrawal_requests' AND column_name = 'gross_amount') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN gross_amount numeric DEFAULT 0;
    END IF;

    -- NEW: Withdrawal Method
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'withdrawal_requests' AND column_name = 'withdrawal_method') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN withdrawal_method text DEFAULT 'Gcash';
    END IF;

    -- NEW: Notes
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'withdrawal_requests' AND column_name = 'notes') THEN
        ALTER TABLE withdrawal_requests ADD COLUMN notes text;
    END IF;
END $$;

-- 2. Create the Fees Log Table (Idempotent)
CREATE TABLE IF NOT EXISTS withdrawal_fees_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  withdrawal_request_id bigint REFERENCES withdrawal_requests(id) ON DELETE CASCADE,
  agent_id bigint, -- Removed FK constraint to avoid "no unique constraint" error
  processing_fee numeric NOT NULL DEFAULT 0,
  tax numeric NOT NULL DEFAULT 0,
  total_deduction numeric NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT NOW()
);

-- 3. Update the Function
CREATE OR REPLACE FUNCTION withdraw_commission(
  p_agent_id bigint,
  p_amount numeric,
  p_method text DEFAULT 'Gcash',
  p_notes text DEFAULT '' -- NEW PARAMETER
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_balance numeric;
  v_month int;
  v_year int;
  
  -- Deductions
  v_tax numeric;
  v_fee numeric := 50; -- Fixed processing fee
  v_net numeric;
  v_request_id bigint; -- To store the new request ID
BEGIN
  -- 1. Check current balance
  SELECT balance INTO v_balance
  FROM agent_wallets
  WHERE agent_id = p_agent_id;

  IF v_balance IS NULL OR v_balance < p_amount THEN
    RAISE EXCEPTION 'Insufficient funds (You requested %, but only have %)', p_amount, COALESCE(v_balance, 0);
  END IF;

  -- 1.5. CHECK FOR EXISTING PENDING REQUESTS (Anti-Spam / Single Request Rule)
  IF EXISTS (SELECT 1 FROM withdrawal_requests WHERE agent_id = p_agent_id AND status = 'pending') THEN
    RAISE EXCEPTION 'You already have a pending withdrawal request. Please wait for it to be processed.';
  END IF;

  -- 2. Calculate Deductions
  -- Tax is 10% of the GROSS withdrawal amount
  v_tax := p_amount * 0.10;
  
  -- Net is Amount - Tax - Fee
  v_net := p_amount - v_tax - v_fee;

  IF v_net < 0 THEN
    RAISE EXCEPTION 'Withdrawal amount too low to cover fees and tax.';
  END IF;

  -- 3. Determine current period
  v_month := EXTRACT(MONTH FROM NOW());
  v_year := EXTRACT(YEAR FROM NOW());

  -- 4. Deduct TOTAL GROSS AMOUNT from wallet
  UPDATE agent_wallets
  SET balance = balance - p_amount
  WHERE agent_id = p_agent_id;

  -- 5. Create Withdrawal Request (Capture ID)
  -- UPDATED: 'amount' column now stores NET (Receivable) amount.
  -- 'gross_amount' stores the original requested amount.
  INSERT INTO withdrawal_requests (
    agent_id, 
    amount,        -- NET Amount (Payable)
    gross_amount,  -- Gross Amount
    tax,           -- 10%
    fee,           -- 50
    net_amount,    -- (Redundant now, but keeping for compatibility)
    period_month, 
    period_year, 
    status, 
    withdrawal_method, 
    notes,         -- NEW
    created_at
  )
  VALUES (
    p_agent_id, 
    v_net,         -- Store NET here
    p_amount,      -- Store GROSS here
    v_tax,
    v_fee,
    v_net,
    v_month, 
    v_year, 
    'pending', 
    p_method,      
    p_notes,       -- NEW
    NOW()
  )
  RETURNING id INTO v_request_id;

  -- 6. Insert into Fees Log
  INSERT INTO withdrawal_fees_log (
    withdrawal_request_id,
    agent_id,
    processing_fee,
    tax,
    total_deduction
  )
  VALUES (
    v_request_id,
    p_agent_id,
    v_fee,
    v_tax,
    v_fee + v_tax
  );

END;
$$;
